import { PrimeReactProvider } from 'primereact/api'

import type { Viewport } from 'next'
import 'primereact/resources/themes/lara-dark-blue/theme.css'
import 'primeicons/primeicons.css'

import './globals.css'
import '../assets/_global.scss'

import { Providers } from './providers'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export const viewport: Viewport = {
  colorScheme: 'dark',
  themeColor: '#111827',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="p-dark">
      <body className="nuc-system">
        <Providers>
          <PrimeReactProvider value={{ ripple: true }}>
            {children}
          </PrimeReactProvider>
        </Providers>
      </body>
    </html>
  )
}
