import { PrimeReactProvider } from 'primereact/api'
import 'primereact/resources/themes/lara-dark-blue/theme.css'
import 'primeicons/primeicons.css'
import {NucEntityChart} from '../../../next/modules/nuc_charts/atomic/template/entity-chart/index.tsx'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <PrimeReactProvider>
          {children}
          {/* Передаємо тестові пропси, щоб компонент не впав */}
          <div style={{ height: '400px', padding: '20px' }}>
             <NucEntityChart 
                type="bar" 
                chartMethodType="annual" 
                example={true} 
                chartClass="test-chart"
             />
          </div>
        </PrimeReactProvider>
      </body>
    </html>
  )
}