import { PrimeReactProvider } from 'primereact/api'
import 'primereact/resources/themes/lara-dark-blue/theme.css'
import 'primeicons/primeicons.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <PrimeReactProvider>{children}</PrimeReactProvider>
      </body>
    </html>
  )
}
