import { PrimeReactProvider } from 'primereact/api'
import 'primereact/resources/themes/lara-dark-blue/theme.css'
import 'primeicons/primeicons.css'
import NucTooltip from '../../../next/modules/nuc_tooltip';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <PrimeReactProvider>{children}
          <div style={{ 
            position: 'fixed', 
            bottom: '20px', 
            right: '20px', 
            padding: '20px', 
            background: '#1e293b', 
            borderRadius: '8px',
            border: '1px solid #334155',
            zIndex: 9999 
          }}>
            <p style={{ margin: '0 0 10px 0', fontSize: '12px', color: '#94a3b8' }}>Debug Tooltip:</p>
            
            <NucTooltip value="test" position="left" showDelay={500} hideDelay={200}>
              <button style={{ 
                padding: '8px 16px', 
                background: '#3b82f6', 
                color: 'white', 
                border: 'none', 
                borderRadius: '4px',
                cursor: 'pointer' 
              }}>
                Hover me
              </button>
            </NucTooltip>
          </div>
        </PrimeReactProvider>
      </body>
    </html>
  )
}
