export interface SwiperInterface {
  slides?: SwiperSlideInterface[]
  slidesPerView?: number
  slidesPerGroup?: number
  spaceBetween?: number
  speed?: number
  modules?: unknown[]
  navigation?: boolean
  pagination?: unknown
  scrollbar?: unknown
  allowSlideNext?: boolean
  allowSlidePrev?: boolean
  allowTouchMove?: boolean
  autoHeight?: boolean
  autoplay?: unknown
  breakpoints?: unknown
  breakpointsBase?: 'container' | 'window'
  cardsEffect?: unknown
  centerInsufficientSlides?: boolean
  centeredSlides?: boolean
  centeredSlidesBounds?: boolean
  containerModifierClass?: string
  controller?: unknown
  coverflowEffect?: unknown
  createElements?: boolean
  creativeEffect?: unknown
  cssMode?: boolean
  cubeEffect?: unknown
  direction?: string
  edgeSwipeDetection?: string | boolean
  edgeSwipeThreshold?: number
  effect?: string
  enabled?: boolean
  eventsPrefix?: string
  fadeEffect?: unknown
  flipEffect?: unknown
  focusableElements?: string
  followFinger?: boolean
  freeMode?: unknown
  grid?: unknown
  hashNavigation?: unknown
  height?: number
  history?: unknown
  init?: boolean
  initialSlide?: number
  injectStyles?: string[]
  injectStylesUrls?: string[]
  keyboard?: unknown
  lazyPreloadPrevNext?: number
  lazyPreloaderClass?: string
  longSwipes?: boolean
  longSwipesMs?: number
  longSwipesRatio?: number
  loop?: boolean
  loopAddBlankSlides?: boolean
  loopAdditionalSlides?: number
  loopPreventsSliding?: boolean
  maxBackfaceHiddenSlides?: number
  mousewheel?: unknown
  nested?: boolean
  noSwiping?: boolean
  noSwipingClass?: string
  noSwipingSelector?: string
  normalizeSlideIndex?: boolean
  observeParents?: boolean
  observeSlideChildren?: boolean
  observer?: boolean
  on?: object
  onAny?: unknown
  oneWayMovement?: boolean
  parallax?: unknown
  passiveListeners?: boolean
  preventClicks?: boolean
  preventClicksPropagation?: boolean
  preventInteractionOnTransition?: boolean
  resistance?: boolean
  resistanceRatio?: number
  resizeObserver?: boolean
  rewind?: boolean
  roundLengths?: boolean
  runCallbacksOnInit?: boolean
  setWrapperSize?: boolean
  shortSwipes?: boolean
  simulateTouch?: boolean
  slideActiveClass?: string
  slideBlankClass?: string
  slideClass?: string
  slideFullyVisibleClass?: string
  slideNextClass?: string
  slidePrevClass?: string
  slideToClickedSlide?: boolean
  slideVisibleClass?: string
  slidesOffsetAfter?: number
  slidesOffsetBefore?: number
  slidesPerGroupAuto?: boolean
  slidesPerGroupSkip?: number
  swipeHandler?: unknown
  swiperElementNodeName?: string
  threshold?: number
  thumbs?: unknown
  touchAngle?: number
  touchEventsTarget?: 'container' | 'wrapper'
  touchMoveStopPropagation?: boolean
  touchRatio?: number
  touchReleaseOnEdges?: boolean
  touchStartForcePreventDefault?: boolean
  touchStartPreventDefault?: boolean
  uniqueNavElements?: boolean
  updateOnWindowResize?: boolean
  url?: string
  userAgent?: string
  virtual?: unknown
  virtualTranslate?: boolean
  watchOverflow?: boolean
  watchSlidesProgress?: boolean
  width?: number
  wrapperClass?: string
  zoom?: unknown
}

export interface SwiperSlideInterface {
  url?: string
  prefix?: string
  image?: string
}
